#!/bin/bash
set -e

PUID=${PUID:-1000}
PGID=${PGID:-1000}

if [ -n "$TZ" ] && [ -f "/usr/share/zoneinfo/$TZ" ]; then
    ln -sf "/usr/share/zoneinfo/$TZ" /etc/localtime
    echo "$TZ" > /etc/timezone
fi

generate_server_id() {
    cat /proc/sys/kernel/random/uuid | tr -d '-' | head -c 32
}

if [ ! -f /config/stash_jellyfin_proxy.conf ]; then
    echo "Creating default config file..."
    SERVER_ID_VALUE=$(generate_server_id)
    cat > /config/stash_jellyfin_proxy.conf << EOF
# Stash-Jellyfin Proxy Configuration
# Generated by Docker container

# Stash server settings
STASH_URL = https://stash:9999
STASH_API_KEY = your_api_key_here

# Proxy server settings
PROXY_BIND = 0.0.0.0
PROXY_PORT = 8096
UI_PORT = 8097
PROXY_API_KEY = 

# Authentication (used by Infuse to connect) - CHANGE THESE!
SJS_USER = admin
SJS_PASSWORD = CHANGE_ME

# Server identification (must be unique, do not change after setup)
SERVER_ID = ${SERVER_ID_VALUE}

# Library settings
TAG_GROUPS = 
LATEST_GROUPS = Scenes

# Server display name
SERVER_NAME = Stash Media Server

# Connection settings
STASH_TIMEOUT = 30
STASH_RETRIES = 3

# GraphQL endpoint path
STASH_GRAPHQL_PATH = /graphql

# TLS verification (set to false for self-signed certs in Docker)
STASH_VERIFY_TLS = false

# Feature toggles
ENABLE_FILTERS = true
ENABLE_IMAGE_RESIZE = true
ENABLE_TAG_FILTERS = false
ENABLE_ALL_TAGS = false
IMAGE_VERSION = 0

# Pagination
DEFAULT_PAGE_SIZE = 100
MAX_PAGE_SIZE = 500

# Image cache
IMAGE_CACHE_MAX_SIZE = 100

# Security
REQUIRE_AUTH_FOR_CONFIG = false

# Logging
LOG_DIR = /config
LOG_FILE = stash_jellyfin_proxy.log
LOG_LEVEL = INFO
LOG_MAX_SIZE_MB = 10
LOG_BACKUP_COUNT = 3
EOF
    echo "Default config created at /config/stash_jellyfin_proxy.conf"
    echo "  SERVER_ID: ${SERVER_ID_VALUE}"
    echo ""
    echo "IMPORTANT: Edit /config/stash_jellyfin_proxy.conf and set:"
    echo "  - STASH_API_KEY (from Stash Settings > Security > API Key)"
    echo "  - STASH_URL (if Stash is not at http://localhost:9999)"
    echo "  - SJS_PASSWORD (for Infuse login)"
    echo ""
fi

if ! getent group "${PGID}" >/dev/null 2>&1; then
    groupadd -g "${PGID}" proxy 2>/dev/null || true
fi

if ! getent passwd "${PUID}" >/dev/null 2>&1; then
    useradd -u "${PUID}" -g "${PGID}" -M -s /bin/bash proxy 2>/dev/null || true
fi

chown -R "${PUID}:${PGID}" /config
chown -R "${PUID}:${PGID}" /app

export CONFIG_FILE=/config/stash_jellyfin_proxy.conf
export LOG_DIR=/config

echo "Starting Stash-Jellyfin Proxy..."
echo "  PUID: ${PUID}"
echo "  PGID: ${PGID}"
echo "  TZ: ${TZ:-UTC}"
echo "  Config: ${CONFIG_FILE}"

exec gosu "${PUID}:${PGID}" "$@"